spring:
  rabbitmq:
    host: localhost
    port: 8080
    username: guest
    password: guest
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
    trace-id128: true
  zipkin:
    enabled: true
    sender:
      type: web
    base-url: http://localhost:9411/

server:
  port: 8301

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://peer1:8101/eureka