spring:
  application:
    name: eureka-producer
  cloud:
    service-registry:
      auto-registration:
        enabled: true

server:
  port: 8202

eureka:
  client:
#    enabled: false
    service-url:
      defaultZone: http://peer1:8101/eureka
