spring:
  application:
    name: config-server
  rabbitmq:
    port: 8080
# 本地文件方式
#  profiles:
#    active: native
  cloud:
    config:
      server:
#        native:
#          search-locations: file:E:/properties/
        git:
          # 配置git仓库的地址
          uri: https://github.com/H-hao/springcloud-tutoiral
#          username:
#          password:
          search-paths: config-repository # git仓库地址下的相对地址，可以配置多个，用,分割。
    bus:
      enabled: true
      trace:
        enabled: true

server:
  port: 8500

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://peer1:8101/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'


