#集群时，在注册的时候，配置文件中的spring.application.name必须一致，否则他们只是两个单独的注册中心，他们之间无法进行 peer-to-peer 通信；
spring:
  application:
    name: eureka-server

server:
  port: 8102

# 当前 eureka 实例所在域名
eureka:
  instance:
    hostname: peer2
    prefer-ip-address: true

# 在默认设置下，该服务注册中心也会将自己作为客户端来尝试注册它自己，所以我们需要禁用它的客户端注册行为
# 注意：如果配置 eureka-server 为集群，那么需要开启这两个配置为 true，
# 因为他们需要向兄弟节点进行注册以实现集群环境，否则仅仅是两个单节点的注册中心；在页面上处于 unavailable-replicas 下；
  client:
    # 表示是否将自己注册到 Eureka Server
    register-with-eureka: true
    # 表示是否从 Eureka Server 获取注册信息
    fetch-registry: true
    # 设置与 Eureka Server 交互的地址，查询服务和注册服务都需要依赖这个地址
    service-url.defaultZone: http://peer1:8101/eureka,http://peer3:8103/eureka