spring:
  application:
    name: eureka-server

server:
  port: 8103

eureka:
  instance:
    hostname: peer3
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: http://peer1:8101/eureka,http://peer2:8102/eureka