spring:
  application:
    name: api-gateway-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - Elapsed=true
      routes:
        - id: feign
          uri: lb://EUREKA-CONSUMER-FEIGN
          order: 0
          predicates:
            - Path=/a/** # 可用于缩短 url
          filters:
            - StripPrefix=1
#            - Elapsed=true # 作用于 ElapsedGatewayFilterFactory
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@remoteAddrKeyResolver}' # 用于限流的键的解析器的 Bean 对象名字，从 spring 容器中获取指定名称的bean，
                redis-rate-limiter.burstCapacity: 5 # 令牌桶容量
                redis-rate-limiter.replenishRate: 1 # 令牌桶每秒填充平均速率
            - AddResponseHeader=X-Response-Default-Foo, Default-Bar
  redis:
    host: localhost
    port: 6379
    database: 0

server:
  port: 8601

eureka:
  client:
    service-url:
      defaultZone: http://peer1:8101/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.cloud.gateway: debug
